### ISSUE TITLE
Remove selfdestructs

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-eth#25]
Until we support initialization of logic contracts in zOS, self-destructable contracts are open to being _accidentally killed_ (see https://github.com/OpenZeppelin/openzeppelin-zos/blob/master/contracts/drafts/BreakInvariantBounty.sol#L68 for an example). 

We should remove all selfdestruct calls from the oz-zos codebase.

Thanks @cwhinfrey for the report!

**Comment by cwhinfrey** [comment]
Sure thing! 👍

**Comment by nventuro** [comment]
What do you propose we do in this scenario? `selfdestruct` sorf ot makes sense there (though it could be argued it also makes sense in the `claim` scenario), and I'd prefer not to introduce further differences between oz and oz-zos. I'd leave it out of this release altogether, and wait until that is fixed upstream (https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1384).

**Comment by spalladino** [comment]
@nventuro I'd either remove the contract altogether as you mention, or change the `selfdestruct` to a `owner().transfer(this.balance)`, since the behaviour we want is to transfer all funds to the owner.

**Comment by nventuro** [comment]
This has now been fixed in `openzeppelin-solidity` (https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1385), and will go into 2.0-rc4. I'll keep it out of this `oz-zos` release, and add it back once we merge rc4 here.

**Comment by nventuro** [comment]
Closed via https://github.com/OpenZeppelin/openzeppelin-eth/pull/28
