### ISSUE TITLE
setTokenURI not accessible when using stdlib MintableERC721Token

### ISSUE THREAD

**Issue by haraldini** [OpenZeppelin/openzeppelin-eth#3]
There seems to be no way to call setTokenURI for ERC721 tokens when using stdlib.

MintableERC721Token only exposes `address` and `tokenId`
https://github.com/OpenZeppelin/openzeppelin-zos/blob/6e5596e80c6bc6746ed02be89c7e50ba771edec6/contracts/token/ERC721/MintableERC721Token.sol#L16

ERC721 `setTokenUri` is internal only
https://github.com/OpenZeppelin/openzeppelin-zos/blob/6e5596e80c6bc6746ed02be89c7e50ba771edec6/contracts/token/ERC721/ERC721Token.sol#L106

This behaviour is fine when inheriting from ERC721, but becomes inaccessbile when using an already deployed instance.
There is no other public method available to set the uri.

**Comment by frangio** [comment]
Thanks for reporting @haraldini!

This will be fixed once we update to 2.0 (#2), because the new `ERC721Mintable` has a `mintWithTokenURI` function.

**Comment by frangio** [comment]
Fixed now with [`ERC721MetadataMintable`](https://github.com/OpenZeppelin/openzeppelin-eth/blob/v2.1.3/contracts/token/ERC721/ERC721MetadataMintable.sol#L26).
