### ISSUE TITLE
Issue with Solidity 0.5 and ERC20.sol

### ISSUE THREAD

**Issue by snario** [OpenZeppelin/openzeppelin-eth#42]
I think this is probably just one of many upgrading issues, but it would be nice if there was a way to handle this in codebases that are upgrading to solidity 0.5.

```solidity
openzeppelin-eth/contracts/token/ERC20/ERC20.sol:189:13:
TypeError: Operator != not compatible with types address and int_const 0
    require(account != 0);
```

**Comment by nventuro** [comment]
Hey @snario! OpenZeppelin has not yet upgraded to Solidity 0.5 (see [here](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1498) for some more discussion), so sadly if you do upgrade there'll be some changes you need to do to the code (in that case, replace the `0` with `address(0)`). We're planning up upgrading to 0.5 once truffle releases a stable version supporting it.

Hope that helps! Feel free to continue this discussion on that issue I linked.

**Comment by renexdev** [comment]
Following the zos tutorial in MyLinkedContract.sol I came to the same issue using Solidity 0.5. With the current "openzeppelin-eth": "^2.1.2" version I could get rid of the error modifying the require line with 
require(address(token) != address(0));
Cheers

**Comment by yalegria** [comment]
I am using Solidity 0.8.11 and this is still an issue. Casting the integer value works `address(0)`.
